auth:
  enabled: true
  groupMembership:
    service: EXTERNAL

server:
  address: 0.0.0.0

fiat:
  admin:
    roles:
      - admin
  getAllEnabled: true
  writeMode:
    enabled: true
  cache:
    expiresAfterWriteSeconds: 0

logging:
  level:
    root: DEBUG
