spectator:
  applicationName: ${spring.application.name}
  webEndpoint:
    enabled: false

dockerRegistry.enabled: true

jenkins:
  enabled: true
  masters:
  - name: jenkins-CI-master
    address: http://www.313.co.kr:38080
    username: spinnaker
    password: qwe123
  - name: jenkins-CD-master
    address: http://www.313.co.kr:38080
    username: spinnaker
    password: qwe123

travis:
  enabled: false
  masters: []

server:
  port: ${services.igor.port:8088}
  address: ${services.igor.host:localhost}

redis:
  connection: ${services.redis.baseUrl:redis://localhost:6379}

logging:
  level:
    root: INFO